# Generated by Django 5.2.7 on 2025-11-09 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='App.usuario')),
            ],
            options={
                'verbose_name': 'Histórico de Usuario',
                'verbose_name_plural': 'Históricos de Usuarios',
                'ordering': ['-modified_at'],
            },
        ),
    ]
