# Generated by Django 5.0.6 on 2025-11-12 22:19

import App.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_usuario_options_usuario_password_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Administrador'), ('Manager', 'Gerente'), ('Employee', 'Empleado')], default='Employee', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.AlterModelOptions(
            name='importaudit',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Auditoría de Importación', 'verbose_name_plural': 'Auditorías de Importaciones'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-created_at'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='importaudit',
            name='processing_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuariohistorico',
            name='change_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariohistorico',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importaudit',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='imports/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='importaudit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente revisión'), ('VALIDATED', 'Validado'), ('IMPORTING', 'Importando'), ('IMPORTED', 'Importado exitosamente'), ('CANCELLED', 'Cancelado'), ('FAILED', 'Falló')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='importaudit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.PositiveIntegerField(blank=True, help_text='Edad en años (0-150)', null=True, validators=[App.models.validate_edad], verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='Correo electrónico único', max_length=254, unique=True, validators=[App.models.validate_email_domain], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(help_text='Nombre del usuario', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(help_text='Apellido del usuario', max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Formato: +56912345678', max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido. Use: +56912345678', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='App_usuario_email_f3dd43_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['telefono'], name='App_usuario_telefon_158e64_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['-created_at'], name='App_usuario_created_4db692_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
