# Generated by Django 5.0.6 on 2025-11-13 20:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_userprofile_alter_importaudit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='importaudit',
            name='error_count',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de filas con errores', verbose_name='Errores'),
        ),
        migrations.AlterField(
            model_name='importaudit',
            name='errors',
            field=models.JSONField(blank=True, default=list, verbose_name='Detalle de Errores'),
        ),
        migrations.AlterField(
            model_name='importaudit',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='imports/%Y/%m/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='importaudit',
            name='filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del Archivo'),
        ),
        migrations.AlterField(
            model_name='importaudit',
            name='imported_count',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de usuarios nuevos creados', verbose_name='Registros Creados'),
        ),
        migrations.AlterField(
            model_name='importaudit',
            name='processing_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Tiempo de Procesamiento'),
        ),
        migrations.AlterField(
            model_name='importaudit',
            name='row_count',
            field=models.PositiveIntegerField(default=0, help_text='Total de filas en el archivo', verbose_name='Total de Filas'),
        ),
        migrations.AlterField(
            model_name='importaudit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente revisión'), ('VALIDATED', 'Validado'), ('IMPORTING', 'Importando'), ('IMPORTED', 'Importado exitosamente'), ('CANCELLED', 'Cancelado'), ('FAILED', 'Falló')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='importaudit',
            name='updated_count',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de usuarios existentes actualizados', verbose_name='Registros Actualizados'),
        ),
        migrations.AlterField(
            model_name='importaudit',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Carga'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hire_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Contratación'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verificado'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrador'), ('Manager', 'Gerente'), ('Employee', 'Empleado')], default='Employee', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Usuario activo en el sistema', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='usuariohistorico',
            name='change_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Razón del Cambio'),
        ),
        migrations.AlterField(
            model_name='usuariohistorico',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='usuariohistorico',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuariohistorico',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuariohistorico',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuariohistorico',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuariohistorico',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='usuariohistorico',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por'),
        ),
        migrations.AlterField(
            model_name='usuariohistorico',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuariohistorico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='App.usuario', verbose_name='Usuario'),
        ),
    ]
