# Generated by Django 5.0.6 on 2025-11-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_usuario_password_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(help_text='Contraseña (minimo 6 caracteres)', max_length=128, null=True, verbose_name='Password'),
        ),
    ]
