# Generated by Django 5.0.6 on 2025-11-14 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_usuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'administrador'), ('USER', 'Usuario'), ('GUEST', 'Invitado')], default='GUEST', max_length=55),
        ),
        migrations.AddField(
            model_name='usuario',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.categoria'),
        ),
    ]
