# Generated by Django 5.0.6 on 2025-11-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_categoria_usuario_rol_usuario_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'administrador'), ('USER', 'Usuario')], default='USER', max_length=55),
        ),
    ]
