# Generated by Django 5.0.6 on 2025-11-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
